name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir build
          cp app.py build/
          cp requirements.txt build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flask-build
          path: build/